version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium
    volumes:
      - ./target:/app/target
    entrypoint: ""