version: "3.9"

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome

  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox

  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-chrome
      - selenium-firefox
    environment:
      - CHROME_HOST=selenium-chrome
      - FIREFOX_HOST=selenium-firefox
      - SELENIUM_PORT=4444
    volumes:
      - ./target/allure-results:/app/target/allure-results

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-report
    ports:
      - "127.0.0.1:5050:5050"
    volumes:
      - ./target/allure-results:/app/allure-results
      # Порт открыт ТОЛЬКО на 127.0.0.1 (localhost)
      # Извне сети (с других машин) подключиться нельзя